version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tokencasa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: .deploy/Dockerfile
      target: backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tokencasa
      XRPL_NETWORK: mainnet
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build:
      context: ..
      dockerfile: .deploy/Dockerfile
      target: frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
      NEXT_PUBLIC_XRPL_NETWORK: mainnet
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

